### ISSUE TITLE
Installation fails if numpy is not already installed with python 3.8

### ISSUE THREAD

**Issue by Kerl13** [oxfordcontrol/osqp-python#40] opened 2019-12-07 17:57 UTC
Installation in a fresh python3.8 environment where numpy is not present fails because of the numpy import at the beginning of `setup.py`.

```shell
$ python --version
Python 3.8.0
$ pip --version
pip 19.3.1 from /tmp/venv/lib/python3.8/site-packages/pip (python 3.8)
$ pip install osqp
Collecting osqp
  Using cached https://files.pythonhosted.org/packages/ba/17/49790ce2ce7a6b95cd250642ebc68bd723ddefdd052ee8dcc1e0dcf4ffca/osqp-0.6.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a1pzoqca/osqp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a1pzoqca/osqp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a1pzoqca/osqp/pip-egg-info
         cwd: /tmp/pip-install-a1pzoqca/osqp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a1pzoqca/osqp/setup.py", line 11, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems that this issue had be addressed in PR #2 but that `import numpy` is now back in `setup.py`. Strangely I didn't observe this behavior under python 3.6 and 3.7 so it may be related to python 3.8.

Installing numpy before osqp avoids the problem.

**Comment by arberx** [comment] 2020-02-11 03:10
Can confirm, still an issue with `python3.8`.

**Comment by tgpfeiffer** [comment] 2020-03-18 07:42
Simple way to reproduce:

**Python 3.8**
```
$ docker run --rm python:3.8 pip install "osqp<0.7.0,>=0.6.1"
Collecting osqp<0.7.0,>=0.6.1
  Downloading osqp-0.6.1.tar.gz (211 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8osz6n43/osqp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8osz6n43/osqp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8osz6n43/osqp/pip-egg-info
         cwd: /tmp/pip-install-8osz6n43/osqp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8osz6n43/osqp/setup.py", line 11, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Python 3.7**
```
$ docker run --rm python:3.7 pip install "osqp<0.7.0,>=0.6.1"
Collecting osqp<0.7.0,>=0.6.1
  Downloading osqp-0.6.1-cp37-cp37m-manylinux2010_x86_64.whl (211 kB)
Collecting numpy>=1.7
  Downloading numpy-1.18.2-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting scipy>=0.13.2
  Downloading scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
Building wheels for collected packages: future
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=f9cf8ad3d489cff2b5fbbfddb8fae9e80808023e5352912be4930552dd09ae81
  Stored in directory: /root/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built future
Installing collected packages: numpy, future, scipy, osqp
Successfully installed future-0.18.2 numpy-1.18.2 osqp-0.6.1 scipy-1.4.1
```

So apparently the problem is that there is no `whl` packaged for Python 3.8. `docker run --rm python:3.7 pip install --no-binary :all: "osqp<0.7.0,>=0.6.1"` fails with the same error as the Python 3.8 output above.

**Comment by AtsushiSakai** [comment] 2020-05-07 11:03
cvxpy has a upgrade issue to python3.8 because of this problem...

**Comment by bstellato** [comment] 2020-05-07 16:06
Sorry about the delay, last months were not easy! I am trying to build the wheels for Python 3.8 [here](https://github.com/oxfordcontrol/osqp-wheels). I hope to have it in the next few days. We will have more releases with better deployment tools this summer.

**Comment by bstellato** [comment] 2020-05-07 22:01
pip wheels for python 3.8 are [online](https://pypi.org/project/osqp/0.6.1/)! Could you please try to install it again?

**Comment by Kerl13** [comment] 2020-05-07 22:13
> Could you please try to install it again?

Yep, I can confirm it works now. thanks! :slightly_smiling_face: 

(for the record: tested with python 3.8.2 and pip 20.1)

**Comment by bstellato** [comment] 2020-05-07 22:20
Awesome! Thanks for your patience. I will close the issue. Feel free to reopen it if you have any other problems.

**Closed** 2020-05-07 22:20 UTC

**Comment by Kerl13** [comment] 2020-05-07 22:24
> Awesome! Thanks for your patience.

No worries ;) Thanks for taking the time to fix the issue
